import { Circle, FileText, Home, ShoppingCart, Users } from "react-feather";
import { ACTION, MANAGEMENT, ROLES_APP } from "../../constants/app";
export default [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: <Home size={20} />,
    navLink: "/apps/dashboard/list",
    management: MANAGEMENT.USER,
  },
  {
    id: "products",
    title: "Kho Tour",
    icon: <ShoppingCart size={20} />,
    navLink: "/apps/product",
    management: MANAGEMENT.TOUR,
    children: [
      {
        id: "list",
        title: "Danh sách",
        icon: <Circle size={12} />,
        navLink: "/apps/product/list",
        management: MANAGEMENT.TOUR,
        action: ACTION.VIEW,
      },
      {
        id: "add",
        title: "Thêm",
        icon: <Circle size={12} />,
        navLink: "/apps/product/add",
        management: MANAGEMENT.TOUR,
        action: ACTION.CREATE,
      },
    ],
  },
  {
    id: "invoice",
    title: "Bán hàng",
    icon: <FileText size={20} />,
    navLink: "/apps/invoice",
    management: MANAGEMENT.ORDER,
    children: [
      {
        id: "list",
        title: "Danh sách",
        icon: <Circle size={12} />,
        navLink: "/apps/invoice/list",
        management: MANAGEMENT.ORDER,
        action: ACTION.VIEW,
      },
      {
        id: "add",
        title: "Tạo hoá đơn",
        icon: <Circle size={12} />,
        navLink: "/apps/invoice/add",
        management: MANAGEMENT.ORDER,
        action: ACTION.CREATE,
      },
      {
        id: "payment",
        title: "Tạo thanh toán",
        icon: <Circle size={12} />,
        navLink: "/apps/payment/add",
        management: MANAGEMENT.PAYMENT,
        action: ACTION.UPDATE,
      },
      {
        id: "list",
        title: "Lịch sử thanh toán",
        icon: <Circle size={12} />,
        navLink: "/apps/payment/list",

        management: MANAGEMENT.PAYMENT,
        action: ACTION.VIEW,
      },
    ],
  },
  {
    id: "users",
    title: "Người dùng",
    icon: <Users size={20} />,
    navLink: "/apps/user",
    management: MANAGEMENT.USER,
    children: [
      {
        id: "list",
        title: "Danh sách",
        icon: <Circle size={12} />,
        navLink: "/apps/user/list",
        management: MANAGEMENT.USER,
        action: ACTION.VIEW,
      },
      {
        id: "add",
        title: "Thêm",
        icon: <Circle size={12} />,
        navLink: "/apps/user/add",
        management: MANAGEMENT.USER,
        action: ACTION.CREATE,
      },
    ],
  },
  {
    id: "guest",
    title: "Đại lý",
    icon: <Users size={20} />,
    navLink: "/apps/guest",
    management: MANAGEMENT.USER,
    children: [
      {
        id: "list",
        title: "Danh sách",
        icon: <Circle size={12} />,
        navLink: "/apps/guest/list",
        management: MANAGEMENT.USER,
        action: ACTION.VIEW,
      },
      {
        id: "add",
        title: "Thêm",
        icon: <Circle size={12} />,
        navLink: "/apps/guest/add",
        management: MANAGEMENT.USER,
        action: ACTION.CREATE,
      },
    ],
  },

  {
    id: "dashboard",
    title: "Dashboard",
    icon: <Home size={20} />,
    navLink: "/dashboard",
    role: [ROLES_APP.CUSTOMER],
    isShowTour: true,
  },
  {
    id: "home",
    title: "Kho Tour",
    icon: <Home size={20} />,
    navLink: "/home",
    role: [ROLES_APP.CUSTOMER],
    isShowTour: true,
  },

  {
    id: "home",
    title: "Đơn hàng của tôi",
    icon: <FileText size={20} />,
    navLink: "/my-order",
    role: [ROLES_APP.CUSTOMER],
    isShowTour: true,
  },
  {
    id: "history-payment",
    title: "Lịch sử thanh toán",
    icon: <FileText size={20} />,
    navLink: "/history-payment",
    role: [ROLES_APP.CUSTOMER],
    isShowTour: true,
  },
];
