export const FORMAT_ERROR = {
  DUPLICATED_USER: "Tên đăng nhập đã tồn tại",
  DUPLICATED_USER_EMAIL: "Email đã tồn tại",
  DUPLICATED_USER_PHONE: "Số điện thoại đã tồn tại",
  DUPLICATED_BRAND: "Thương hiệu đã tồn tại",
  DUPLICATED_CATEGORY: "Thể loại sản phẩm đã tồn tại",
  DUPLICATED_USER_INDENTITY_CARD: "Căn cước công dân đã tồn tại",
  DUPLICATED_PRODUCT_SET: "Tập sản phẩm đã tồn tại",
  PRODUCT_EXIST: "Mã tour đã tồn tại",
  CANNOT_UPDATE_PRODUCT_WITH_THIS_QUANTITY: "Không thể cập nhật với SL này",
  OUT_OFF_STOCK: "Hết số lượng",
  PRODUCT_COINCIDE_IN_FILE_EXCEL: "Lỗi trùng sản phẩm trong exce",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  ACCOUNT_DEACTIVE: "Tài khoản đã bị khoá",
  EMAIL_UNREGISTERED: "Email unregistered",
  EMAIL_UNVERIFIED: "Email unverified",
  EMAIL_ALREADY_EXISTS: "Email đã tồn tại",
  CANNOT_UPDATE_CUSTOMER_ORDER:
    "Không thể thay đổi khách hàng vì hoá đơn này đã được thanh toán",
  INVALID_QUANTITY: "Số lượng phải lớn hơn 0",
  PHONE_NUMBER_EXISTS: "Số điện thoại đã tồn tại",
  ACCOUNT_ALREADY_EXISTS: "Tài khoản đã tồn tại",
  OPERATOR_NOT_EXIST: "Điều hành không tồn tại",
  WRONG_PASSWORD: "Sai mật khẩu",
  PRODUCT_TRANSACTION_EXIST: "Product cannot be edited or deleted",
  NOT_ALLOWED: "NOT ALLOWED",
  NOT_AUTH_FOR_THIS_ORDER: "Không có quyền cập nhật hoá đơn này",
  NOT_AUTH_FOR_THIS_PAYMENT: "Không có quyền cho thanh toán này",
  NOT_AUTH_FOR_THIS_PLAN: "Không có quyền cho lập dự toán này",
  NOT_AUTH_FOR_THIS_ACTUAL: "Không có quyền lập quyết toán thanh toán này",
  CANNOT_UPDATE_PRODUCT_DEACTIVE:
    "Không thể DEACTIVE TOUR này vì đã đã có người đặt",

  USERNAME_OR_PASSWORD_NOT_MATCH: "Tên đăng nhập hoặc mật khẩu không đúng",
  SAME_OLD_PASSWORD: "Mật khẩu mới phải khác với mật khẩu cũ",
  INVALID_EMAIL: "Email không hợp lệ",
  OLD_PASSWORD_INCORRECT: "Mật khẩu cũ không chính xác",
  CANNOT_DELETE_PRODUCT: "Không thể xoá vì TOUR này đã được đặt",
  CANNOT_DELETE_ORDER: "Không thể xoá vì ORDER này đã được thanh toán",
};
