export const PREFIX_ID_USER = {
  STAFF: 'NV',
  OPERATOR: 'DH',
  ACCOUNTANT: 'KT',
  CUSTOMER: 'AG',
  ADMIN: 'AD',
  HDV: 'HDV ',
  COMPANYADMIN: 'CTY',
  AGENT: 'DLY',
  MANAGER: 'TP',
  DEPUTY: 'PP',
  PRESIDENT: 'GD',
  VICPRESIDENT: 'PGP',
};

export const UUID_VERSION = '4';
export const FORMAT_DATE = 'DD/MM/YYYY';

export const FORBIDDEN = 'FORBIDDEN';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
export const ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS';
export const PHONE_NUMBER_EXISTS = 'PHONE_NUMBER_EXISTS';
export const CODE_EXISTS = 'CODE_EXISTS';
export const EMAIL_UNVERIFIED = 'EMAIL_UNVERIFIED';
export const EMAIL_UNREGISTERED = 'EMAIL_UNREGISTERED';
export const ACCOUNT_DEACTIVE = 'ACCOUNT_DEACTIVE';
export const ACCOUNT_UNVERIFIED = 'ACCOUNT_UNVERIFIED';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const OLD_TOKEN = 'OLD_TOKEN';
export const OLD_PASSWORD_INCORRECT = 'OLD_PASSWORD_INCORRECT';
export const USERNAME_OR_PASSWORD_NOT_MATCH = 'USERNAME_OR_PASSWORD_NOT_MATCH';
export const AMIS_CODE_EXIST = 'AMIS_CODE_EXIST';
export const SALE_NOT_EXIST = 'SALE_NOT_EXIST';
export const DUPPLICATE_CANCEL_STATUS = 'DUPPLICATE_CANCEL_STATUS';
export const COMPANY_NOT_EXIST = 'COMPANY_NOT_EXIST';
export const STAFF_NOT_EXIST = 'STAFF_NOT_EXIST';
export const CUSTOMER_NOT_EXIST = 'CUSTOMER_NOT_EXIST';
export const CANNOT_UPDATE_CUSTOMER_ORDER = 'CANNOT_UPDATE_CUSTOMER_ORDER';
export const INVALID_QUANTITY = 'INVALID_QUANTITY';
export const INVALID_EXPIRED_HOLD = 'INVALID_EXPIRED_HOLD';
export const ERROR_SYSTEM = 'ERROR_SYSTEM';
export const CUSTOMER_COMPANY_EXISTS = 'CUSTOMER_COMPANY_EXISTS';
